# Generated by Django 4.0.1 on 2022-04-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
