# Generated by Django 4.1.4 on 2022-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name": "Productt"},
        ),
    ]
